// Gyral's diagnostic codes (gyral-c5d.13): generates docs/references/errors.md and errors.json
// from packages/core/src/view/messages.ts, and checks the table against its users.
//   node scripts/errors.mjs          → write both files
//   node scripts/errors.mjs --check  → fail when they are stale, when a code is listed twice,
//                                      when a message(code, …) or docsLink(code) call names a
//                                      code the table lacks or passes a different number of
//                                      arguments than its text has placeholders, or when a code
//                                      is never used (part of `pnpm invariants`)
// Production builds print `Gyral G0010 <arguments…> https://gyral.dev/errors/#G0010`; the
// gyral.dev errors page renders errors.json (or the Markdown) with one anchor per code.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { format } from 'prettier';
import ts from 'typescript';

const ROOT = join(import.meta.dirname, '..');
const SRC = join(ROOT, 'packages/core/src');
const TABLE = join(SRC, 'view/messages.ts');
const MD = join(ROOT, 'docs/references/errors.md');
const JSON_FILE = join(ROOT, 'docs/references/errors.json');
const URL = 'https://gyral.dev/errors/#';

const codeName = (code) => `G${String(code).padStart(4, '0')}`;
/** Placeholder names in order of first appearance (message.ts fills them the same way). */
const placeholders = (text) => [...new Set(Array.from(text.matchAll(/\{(\w+)\}/g), (m) => m[1]))];

const parse = (file) =>
  ts.createSourceFile(file, readFileSync(file, 'utf8'), ts.ScriptTarget.Latest, true);

/** The table's entries in source order, with the `// Group` comment each one follows. */
function readTable(errors) {
  const source = parse(TABLE);
  const entries = [];
  const seen = new Set();
  const visit = (node) => {
    if (ts.isObjectLiteralExpression(node)) {
      let group = '';
      for (const property of node.properties) {
        const comments = ts.getLeadingCommentRanges(source.text, property.pos) ?? [];
        for (const c of comments) group = source.text.slice(c.pos + 2, c.end).trim();
        const code = Number(property.name.getText(source));
        if (seen.has(code)) errors.push(`${codeName(code)} is listed twice in the table`);
        seen.add(code);
        const text = evalString(property.initializer, source);
        entries.push({ code, group, text, args: placeholders(text) });
      }
      return;
    }
    ts.forEachChild(node, visit);
  };
  visit(source);
  return entries;
}

/** A string literal, or literals joined with `+`. */
function evalString(node, source) {
  if (ts.isStringLiteralLike(node)) return node.text;
  if (ts.isBinaryExpression(node) && node.operatorToken.kind === ts.SyntaxKind.PlusToken) {
    return evalString(node.left, source) + evalString(node.right, source);
  }
  if (ts.isParenthesizedExpression(node)) return evalString(node.expression, source);
  throw new Error(`messages.ts: not a plain string: ${node.getText(source)}`);
}

const sourceFiles = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory()
      ? sourceFiles(join(dir, e.name))
      : e.name.endsWith('.ts') && !e.name.endsWith('.d.ts')
        ? [join(dir, e.name)]
        : [],
  );

/** Every message(code, …) and docsLink(code) call in core's source. */
function readUses(errors) {
  const uses = [];
  for (const file of sourceFiles(SRC)) {
    if (file === TABLE || file.endsWith('view/message.ts')) continue;
    const source = parse(file);
    const visit = (node) => {
      if (
        ts.isCallExpression(node) &&
        ts.isIdentifier(node.expression) &&
        (node.expression.text === 'message' || node.expression.text === 'docsLink')
      ) {
        const [first] = node.arguments;
        const where = `${relative(ROOT, file)}:${String(source.getLineAndCharacterOfPosition(node.pos).line + 1)}`;
        if (first === undefined || !ts.isNumericLiteral(first)) {
          errors.push(
            `${where}: ${node.expression.text}() needs a literal code as its first argument`,
          );
        } else {
          const args = node.expression.text === 'message' ? node.arguments.length - 1 : undefined;
          uses.push({ code: Number(first.text), args, where });
        }
      }
      ts.forEachChild(node, visit);
    };
    visit(source);
  }
  return uses;
}

function markdown(entries) {
  const lines = [
    '# Gyral error codes',
    '',
    '<!-- Generated by `node scripts/errors.mjs` from packages/core/src/view/messages.ts. Do not edit. -->',
    '',
    'Development builds of `@gyral/core` print each message in full. Production builds print its',
    'code, its arguments (in the order of the placeholders below) and a link here:',
    '`Gyral G0010 my-cart Increment https://gyral.dev/errors/#G0010`. The table is',
    '[errors.json](errors.json) (gyral-c5d.13).',
  ];
  let group;
  for (const e of entries) {
    if (e.group !== group) {
      group = e.group;
      lines.push('', `## ${group}`);
    }
    const args = e.args.length === 0 ? 'none' : e.args.map((a) => `\`${a}\``).join(', ');
    lines.push(
      '',
      `### ${codeName(e.code)}`,
      '',
      `> ${e.text.replace(/</g, '\\<')}`,
      '',
      `Arguments: ${args}.`,
    );
  }
  return `${lines.join('\n')}\n`;
}

const json = (entries) =>
  `${JSON.stringify(
    entries.map((e) => ({
      code: codeName(e.code),
      group: e.group,
      message: e.text,
      arguments: e.args,
      url: URL + codeName(e.code),
    })),
    null,
    2,
  )}\n`;

const errors = [];
const entries = readTable(errors);
const byCode = new Map(entries.map((e) => [e.code, e]));
const used = new Set();
for (const use of readUses(errors)) {
  const entry = byCode.get(use.code);
  used.add(use.code);
  if (entry === undefined) errors.push(`${use.where}: ${codeName(use.code)} is not in messages.ts`);
  else if (use.args !== undefined && use.args !== entry.args.length) {
    errors.push(
      `${use.where}: ${codeName(use.code)} takes ${String(entry.args.length)} argument(s) ` +
        `(${entry.args.join(', ')}), got ${String(use.args)}`,
    );
  }
}
for (const e of entries) {
  if (!used.has(e.code))
    errors.push(`${codeName(e.code)} is never used; remove it (codes are never reused)`);
}

// Formatted as `pnpm format` would, so the check and Prettier agree.
const outputs = [
  [
    MD,
    await format(markdown(entries), { parser: 'markdown', printWidth: 100, proseWrap: 'preserve' }),
  ],
  [JSON_FILE, await format(json(entries), { parser: 'json' })],
];
if (process.argv.includes('--check')) {
  for (const [file, text] of outputs) {
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      // missing: stale
    }
    if (current !== text)
      errors.push(`${relative(ROOT, file)} is stale: run node scripts/errors.mjs`);
  }
  if (errors.length > 0) {
    console.error(errors.map((e) => `errors: ${e}`).join('\n'));
    process.exit(1);
  }
  console.log(`errors: ${String(entries.length)} codes, docs current`);
} else {
  if (errors.length > 0) {
    console.error(errors.map((e) => `errors: ${e}`).join('\n'));
    process.exit(1);
  }
  for (const [file, text] of outputs) writeFileSync(file, text);
  console.log(`errors: wrote ${relative(ROOT, MD)} and ${relative(ROOT, JSON_FILE)}`);
}
