/// <reference types="node" />
// Writes a new app: copies templates/<name>/ and generates its package.json.
import { cp, mkdir, readdir, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Template } from './args.js';

/** templates/ ships next to dist/ in the tarball (and next to src/ in the repo). */
export const TEMPLATES_DIR = fileURLToPath(new URL('../templates/', import.meta.url));

/**
 * Versions the templates are tested with (this repo's own toolchain). `@gyral/*` is lockstep
 * with create-gyral itself, so the app gets the release it was generated by.
 */
const TOOLS = {
  vite: '^8.3.2',
  vitest: '^5.0.3',
  '@vitest/browser-playwright': '^5.0.3',
  playwright: '^1.63.0',
  typescript: '^6.0.3',
  '@types/node': '^24.19.1',
  hono: '^4.13.13',
  '@hono/node-server': '^2.1.3',
  tsx: '^4.23.15',
} as const;

type Tool = keyof typeof TOOLS;
const pick = (names: readonly Tool[]): Record<string, string> =>
  Object.fromEntries(names.map((name) => [name, TOOLS[name]]));

export interface Manifest {
  readonly name: string;
  readonly private: true;
  readonly version: string;
  readonly type: 'module';
  readonly scripts: Readonly<Record<string, string>>;
  readonly dependencies: Readonly<Record<string, string>>;
  readonly devDependencies: Readonly<Record<string, string>>;
}

/** The generated app's package.json. */
export function manifest(template: Template, name: string, gyralVersion: string): Manifest {
  const gyral = `^${gyralVersion}`;
  const common = { name, private: true, version: '0.0.0', type: 'module' } as const;
  if (template === 'basic') {
    return {
      ...common,
      scripts: {
        dev: 'vite',
        build: 'tsc --noEmit && vite build',
        preview: 'vite preview',
        test: 'vitest run',
        typecheck: 'tsc --noEmit',
      },
      dependencies: { '@gyral/core': gyral },
      devDependencies: {
        '@gyral/testing': gyral,
        ...pick(['@vitest/browser-playwright', 'playwright', 'typescript', 'vite', 'vitest']),
      },
    };
  }
  return {
    ...common,
    scripts: {
      dev: 'tsx server/dev.ts',
      build: 'tsc --noEmit && vite build && tsx server/prerender.ts',
      preview: 'tsx server/prod.ts',
      test: 'vitest run',
      typecheck: 'tsc --noEmit',
    },
    dependencies: {
      '@gyral/core': gyral,
      '@gyral/ssr': gyral,
      ...pick(['@hono/node-server', 'hono']),
    },
    devDependencies: {
      '@gyral/testing': gyral,
      ...pick(['@types/node', 'tsx', 'typescript', 'vite', 'vitest']),
    },
  };
}

/** Entries that may already exist in a target directory. */
const HARMLESS = new Set(['.git', '.DS_Store', 'Thumbs.db']);

/** True when `dir` is missing or holds nothing but harmless entries. */
export async function isEmptyDir(dir: string): Promise<boolean> {
  try {
    return (await readdir(dir)).every((entry) => HARMLESS.has(entry));
  } catch (error) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return true;
    throw error;
  }
}

export interface ScaffoldOptions {
  readonly targetDir: string;
  readonly template: Template;
  readonly packageName: string;
  readonly gyralVersion: string;
}

/** Copies the template and writes package.json. Refuses a non-empty directory. */
export async function scaffold(options: ScaffoldOptions): Promise<void> {
  const { targetDir, template } = options;
  if (!(await isEmptyDir(targetDir))) {
    throw new Error(`${targetDir} is not empty. Choose a new directory or empty this one.`);
  }
  await mkdir(targetDir, { recursive: true });
  await cp(join(TEMPLATES_DIR, template), targetDir, { recursive: true });
  // npm never publishes a file named .gitignore, so the template ships it as _gitignore.
  await rename(join(targetDir, '_gitignore'), join(targetDir, '.gitignore'));
  const pkg = manifest(template, options.packageName, options.gyralVersion);
  await writeFile(join(targetDir, 'package.json'), `${JSON.stringify(pkg, null, 2)}\n`);
}
